// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;



[Table("Booking")]
public partial class Booking
{
    [Key]
    public int Id { get; set; }

    public int LokaleId { get; set; }

    public int BrugerId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Starttid { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Sluttid { get; set; }

    public bool Smartboard { get; set; }

    [ForeignKey("BrugerId")]
    [InverseProperty("Bookings")]
    public virtual Bruger Bruger { get; set; }

    [ForeignKey("LokaleId")]
    [InverseProperty("Bookings")]
    public virtual Lokale Lokale { get; set; }

    public override string ToString()
    {
        return $"[Booking {Id}] {Bruger.Navn} har booket {Lokale.Id} fra {Starttid}, til {Sluttid} og de har valgt {Smartboard} fra {Starttid} til {Sluttid}";
    }

    //TODO bruger id skal ændres til navn 
    public static Booking Construct(int brugerid, int lokaleId, DateTime starttid, DateTime sluttid, bool smartboard)
    {
        return new Booking {BrugerId = brugerid, LokaleId = lokaleId, Starttid = starttid, Sluttid = sluttid, Smartboard = smartboard };
    }
}