// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models;

[Table("Booking")]
public partial class Booking
{
    [Key]
    public int Id { get; set; }

    public int LokaleId { get; set; }

    public int BrugerId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Starttid { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Sluttid { get; set; }

    public bool Smartboard { get; set; }

    [ForeignKey("BrugerId")]
    [InverseProperty("Bookings")]
    public virtual Bruger Bruger { get; set; }

    [ForeignKey("LokaleId")]
    [InverseProperty("Bookings")]
    public virtual Lokale Lokale { get; set; }
}