// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models;

[Table("Bruger")]
public partial class Bruger
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Navn { get; set; }

    public int Telefon { get; set; }

    [Required]
    [StringLength(50)]
    public string Mail { get; set; }

    [Required]
    [StringLength(50)]
    public string Rolle { get; set; }

    [InverseProperty("Bruger")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [InverseProperty("Bruger")]
    public virtual ICollection<Fag> Fags { get; set; } = new List<Fag>();
}