// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

[Table("Fag")]
public partial class Fag
{
    [Key]
    public int Id { get; set; }

    public int HoldId { get; set; }

    public int BrugerId { get; set; }

    [ForeignKey("BrugerId")]
    [InverseProperty("Fags")]
    public virtual Bruger Bruger { get; set; }

    [ForeignKey("HoldId")]
    [InverseProperty("Fags")]
    public virtual Hold Hold { get; set; }
}