// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;




[Table("Lokale")]
public partial class Lokale 
{
    [Key]
    public int Id { get; set; }

    public bool Smartboard { get; set; }

    [Required]
    [StringLength(50)]
    public int Størrelse { get; set; }

    public int Kapacitet { get; set; }

    [InverseProperty("Lokale")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public override string ToString()
    {
        return $"[Lokale {Id}] Smartboard er {Smartboard}, og lokalets størrelse er til {Størrelse} grupper, og der kan være {Kapacitet}";
    }

    public static Lokale Construct(int id, bool smartboard, int størrelse, int kapacitet)
    {
        return new Lokale { Id = id, Smartboard = smartboard, Størrelse = størrelse, Kapacitet = kapacitet };
    }
}