// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models;

[Table("Lokale")]
public partial class Lokale
{
    [Key]
    public int Id { get; set; }

    public bool Smartboard { get; set; }

    [Required]
    [StringLength(50)]
    public string Størrelse { get; set; }

    public int Kapacitet { get; set; }

    [InverseProperty("Lokale")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}